source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

require_relative '../node_modules/react-native-unimodules/cocoapods'

# pods that need to use use_framework!
static_framework = ['hpple', 'WKZombie', 'SwiftSoup']

pre_install do |installer|
  installer.pod_targets.each do |pod|
    if static_framework.include?(pod.name)
      def pod.build_type;
        Pod::Target::BuildType.static_framework
      end
    end
  end
end

target 'AO3Client' do
  # Pods for AO3Client
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTBlob',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'RNGestureHandler', :podspec => '../node_modules/react-native-gesture-handler/RNGestureHandler.podspec'
  pod 'RNReanimated', :podspec => '../node_modules/react-native-reanimated/RNReanimated.podspec'
  pod 'RNScreens', :path => '../node_modules/react-native-screens'

  use_unimodules!(exclude: ['expo-facebook'])
  
  # install wkzombie's depedency
  pod 'hpple'

  pod 'WKZombie'
  pod 'SwiftSoup'

end
